from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.enums import (
    TA_CENTER,
    TA_LEFT
)

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)


def footer(canvas, doc):
    canvas.saveState()

    canvas.setFont(
        "Helvetica",
        9
    )

    canvas.drawString(
        30,
        20,
        "Generated by Accounting ERP"
    )

    canvas.drawRightString(
        550,
        20,
        f"Page {canvas.getPageNumber()}"
    )

    canvas.restoreState()


def generate_table_pdf(

        filename: str,

        title: str,

        headers: list,

        data: list,

        report_period: str = "",

        total_in: float = 0,

        total_out: float = 0,

        balance: float = 0

):

    pdf = SimpleDocTemplate(

        filename,

        pagesize=A4,

        leftMargin=30,

        rightMargin=30,

        topMargin=30,

        bottomMargin=40

    )



    styles = getSampleStyleSheet()


    title_style = ParagraphStyle(

        name="TitleStyle",

        parent=styles["Title"],

        fontSize=20,

        textColor=colors.HexColor("#1E3A8A"),

        alignment=TA_CENTER

    )


    subtitle_style = ParagraphStyle(

        name="Subtitle",

        parent=styles["Normal"],

        fontSize=10,

        alignment=TA_CENTER,

        textColor=colors.grey

    )


    normal_style = ParagraphStyle(

        name="NormalStyle",

        parent=styles["Normal"],

        fontSize=11,

        alignment=TA_LEFT

    )


    elements = []


    ####################################
    # TITLE
    ####################################

    elements.append(

        Paragraph(

            title,

            title_style

        )

    )


    elements.append(

        Spacer(

            1,
            5
        )

    )


    ####################################
    # PERIOD
    ####################################

    if report_period:

        elements.append(

            Paragraph(

                f"Period : {report_period}",

                subtitle_style

            )

        )


    elements.append(

        Paragraph(

            f"Generated : {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",

            subtitle_style

        )

    )


    elements.append(

        Spacer(

            1,
            20
        )

    )


    ####################################
    # SUMMARY
    ####################################

    summary_data = [

        ["Total IN", f"₹ {total_in:,.2f}"],

        ["Total OUT", f"₹ {total_out:,.2f}"],

        ["Balance", f"₹ {balance:,.2f}"]

    ]


    summary_table = Table(

        summary_data,

        colWidths=[120,120]

    )


    summary_table.setStyle(

        TableStyle([


            (

                'BACKGROUND',

                (0,0),

                (-1,-1),

                colors.lightgrey

            ),

            (

                'FONTNAME',

                (0,0),

                (-1,-1),

                'Helvetica-Bold'

            ),

            (

                'GRID',

                (0,0),

                (-1,-1),

                1,

                colors.black

            ),

            (

                'FONTSIZE',

                (0,0),

                (-1,-1),

                10

            )


        ])

    )


    elements.append(

        summary_table

    )


    elements.append(

        Spacer(

            1,

            20

        )

    )


    ####################################
    # MAIN TABLE
    ####################################

    table_data = [

        headers

    ]


    table_data.extend(

        data

    )


    table = Table(

        table_data,

        repeatRows=1

    )


    style = [


        (

            'BACKGROUND',

            (0,0),

            (-1,0),

            colors.HexColor("#1E40AF")

        ),


        (

            'TEXTCOLOR',

            (0,0),

            (-1,0),

            colors.white

        ),


        (

            'FONTNAME',

            (0,0),

            (-1,0),

            'Helvetica-Bold'

        ),


        (

            'FONTSIZE',

            (0,0),

            (-1,-1),

            10

        ),


        (

            'GRID',

            (0,0),

            (-1,-1),

            1,

            colors.black

        ),


        (

            'ALIGN',

            (0,0),

            (-1,-1),

            'CENTER'

        )

    ]



    for i in range(

            1,

            len(table_data)

    ):

        bg = (

            colors.whitesmoke

            if i % 2 == 0

            else colors.beige

        )


        style.append(

            (

                'BACKGROUND',

                (0,i),

                (-1,i),

                bg

            )

        )


    table.setStyle(

        TableStyle(

            style

        )

    )


    elements.append(

        table

    )


    ####################################
    # BUILD PDF
    ####################################

    pdf.build(

        elements,

        onFirstPage=footer,

        onLaterPages=footer

    )


    return filename